/**
 * Compliance & Legal UI Components
 * AI disclosure badges, disclaimer banners, consent management
 */

// ─── AI DISCLOSURE BADGE ───
export class AIDisclosure {
  static badge(modelName = 'AI') {
    return `<span class="ai-badge" role="note" aria-label="This content was generated by AI">
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
        <path d="M12 2a4 4 0 0 1 4 4v2h2a2 2 0 0 1 2 2v8a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4v-8a2 2 0 0 1 2-2h2V6a4 4 0 0 1 4-4z"/>
        <circle cx="9" cy="14" r="1"/><circle cx="15" cy="14" r="1"/>
      </svg>
      AI Generated
      <span class="ai-badge-model">${modelName}</span>
    </span>`;
  }

  static disclaimer(context = 'research') {
    const disclaimers = {
      research: 'This analysis is AI-generated for educational purposes. It is not investment advice. Always verify with primary sources and consult a qualified advisor.',
      risk_score: 'Risk scores are algorithmic estimates based on historical data. They cannot predict future events and should not be the sole basis for investment decisions.',
      portfolio: 'Portfolio suggestions are for educational purposes only. They do not constitute personalized financial advice and do not account for your specific financial situation.',
      news: 'Sentiment analysis is automated and may misinterpret context. Read the full article for accurate understanding.',
      recommendation: 'Suggestions are based on interest patterns, not suitability assessment. This is not a recommendation to buy or sell any security.'
    };

    return `<div class="ai-disclaimer" role="note" aria-label="AI content disclaimer">
      <span class="ai-disclaimer-icon" aria-hidden="true">ℹ️</span>
      <p>${disclaimers[context] || disclaimers.research}</p>
    </div>`;
  }

  static confidenceIndicator(score) {
    const level = score >= 0.95 ? 'verified' : score >= 0.8 ? 'high' : score >= 0.6 ? 'medium' : score >= 0.4 ? 'low' : 'estimated';
    const colors = { verified: '#059669', high: '#2563EB', medium: '#D97706', low: '#DC2626', estimated: '#6B7280' };
    return `<span class="confidence-badge" style="--confidence-color: ${colors[level]}" title="Confidence: ${(score * 100).toFixed(0)}%">
      ${level} (${(score * 100).toFixed(0)}%)
    </span>`;
  }
}


// ─── PLATFORM DISCLAIMER BANNER ───
export class DisclaimerBanner {
  constructor() {
    this._inject();
  }

  _inject() {
    if (document.querySelector('.platform-disclaimer')) return;
    if (sessionStorage.getItem('ps_disclaimer_dismissed')) return;

    const banner = document.createElement('div');
    banner.className = 'platform-disclaimer';
    banner.setAttribute('role', 'alert');
    banner.innerHTML = `
      <p><strong>Educational Platform:</strong> PreStocks is not a registered investment advisor. All content is for informational and educational purposes only. Paper trading uses simulated funds.
        <a href="/disclaimer.html">Full Disclaimer</a>
      </p>
      <button class="disclaimer-dismiss" aria-label="Dismiss disclaimer">✕</button>
    `;

    document.body.prepend(banner);
    banner.querySelector('.disclaimer-dismiss').addEventListener('click', () => {
      banner.remove();
      sessionStorage.setItem('ps_disclaimer_dismissed', 'true');
    });
  }
}


// ─── COOKIE CONSENT ───
export class CookieConsent {
  constructor() {
    if (!localStorage.getItem('ps_cookie_consent')) this._show();
  }

  _show() {
    const banner = document.createElement('div');
    banner.className = 'cookie-consent';
    banner.setAttribute('role', 'dialog');
    banner.setAttribute('aria-label', 'Cookie consent');
    banner.innerHTML = `
      <div class="cookie-content">
        <p>We use cookies for authentication and preferences (required) and analytics (optional). <a href="/privacy.html#cookies">Learn more</a></p>
        <div class="cookie-actions">
          <button class="btn btn-sm btn-secondary" id="cookie-reject">Reject Optional</button>
          <button class="btn btn-sm btn-primary" id="cookie-accept">Accept All</button>
        </div>
      </div>
    `;

    document.body.appendChild(banner);

    banner.querySelector('#cookie-accept').addEventListener('click', () => {
      localStorage.setItem('ps_cookie_consent', JSON.stringify({ essential: true, analytics: true, marketing: true, timestamp: new Date().toISOString() }));
      banner.remove();
    });

    banner.querySelector('#cookie-reject').addEventListener('click', () => {
      localStorage.setItem('ps_cookie_consent', JSON.stringify({ essential: true, analytics: false, marketing: false, timestamp: new Date().toISOString() }));
      banner.remove();
    });
  }

  static getConsent() {
    return JSON.parse(localStorage.getItem('ps_cookie_consent') || '{"essential":true,"analytics":false,"marketing":false}');
  }

  static hasAnalyticsConsent() {
    return this.getConsent().analytics === true;
  }
}


// ─── DATA EXPORT / DELETION UI ───
export class PrivacyControls {
  static renderSettingsPanel() {
    return `
      <div class="privacy-settings-panel">
        <h3>Privacy & Data</h3>

        <div class="privacy-option">
          <label class="toggle-label">
            <input type="checkbox" id="ai-data-opt-in" ${this._getAIOptIn() ? 'checked' : ''}>
            <span>Allow anonymized data to improve AI models</span>
          </label>
          <p class="option-description">When enabled, your anonymized interactions help us improve AI accuracy. No personal data is used.</p>
        </div>

        <div class="privacy-option">
          <label class="toggle-label">
            <input type="checkbox" id="analytics-opt-in" ${CookieConsent.hasAnalyticsConsent() ? 'checked' : ''}>
            <span>Analytics cookies</span>
          </label>
          <p class="option-description">Help us understand how you use PreStocks to improve the experience.</p>
        </div>

        <div class="privacy-actions">
          <button class="btn btn-secondary btn-sm" onclick="PrivacyControls.exportData()">Export My Data</button>
          <button class="btn btn-danger btn-sm" onclick="PrivacyControls.deleteAccount()">Delete Account</button>
        </div>
      </div>
    `;
  }

  static async exportData() {
    try {
      const resp = await fetch('/api/compliance/data-export', { method: 'POST', headers: { 'Authorization': `Bearer ${localStorage.getItem('ps_token')}` } });
      const data = await resp.json();
      alert(data.message || 'Export request submitted. Check your email.');
    } catch (e) {
      alert('Failed to request data export. Please try again.');
    }
  }

  static async deleteAccount() {
    if (!confirm('Are you sure? Your account will be deactivated immediately. You have 30 days to cancel.')) return;
    if (!confirm('This is irreversible after 30 days. All your data will be permanently deleted. Continue?')) return;

    try {
      const resp = await fetch('/api/compliance/delete-account', { method: 'POST', headers: { 'Authorization': `Bearer ${localStorage.getItem('ps_token')}` } });
      const data = await resp.json();
      alert(data.message || 'Account deletion initiated.');
      window.location.href = '/';
    } catch (e) {
      alert('Failed to initiate deletion. Please contact privacy@prestocks.io.');
    }
  }

  static _getAIOptIn() {
    return localStorage.getItem('ps_ai_opt_in') !== 'false';
  }
}
